apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-all
  namespace: prod
rules:
- apiGroups: ["", "apps", "batch", "networking.k8s.io", "extensions", "autoscaling"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod_admin
  namespace: prod
subjects:
- kind: User
  name: prod_admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod_view
  namespace: prod
subjects:
- kind: User
  name: prod_view
  apiGroup: ""
roleRef:
  kind: Role
  name: view-all
  apiGroup: ""