apiVersion:  apps/v1
kind:  Deployment
metadata:
  name:  two-nginx-deployment
  labels:
    app:  nginx
spec:
  replicas:  2
  selector:
    matchLabels:
      project:  pod-nginx
  template:
    metadata:
      labels:
        project:  pod-nginx
    spec:
      containers:
        - name:  nginx
          image:  nginx:latest
          ports: 
          - containerPort: 80
